const autogen = require('swagger-autogen')();

const fileOut = './swagger_output.json';
const endpoints = ['./routes/routes'];

const doc = {
    info: {
        version: "1.0.0",
        title: "Driver Service",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:8080",
    basePath: "/users",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Driver",
            "description": "Endpoints"
        }
    ],
}

autogen(fileOut, endpoints, doc);